// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'important_people_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ImportantPeopleModel _$ImportantPeopleModelFromJson(
        Map<String, dynamic> json) =>
    ImportantPeopleModel(
      voterId: json['voterId'],
      title: json['title'],
      first_name: json['first_name'],
      middleName: json['middleName'],
      lastName: json['lastName'],
      serialNo: json['serialNo'],
      gender: json['gender'],
      age: json['age'] as int?,
      dob: json['dob'],
      phone_no: json['phone_no'],
      emailId: json['emailId'],
      relationType: json['relationType'],
      relationFirstName: json['relationFirstName'],
      relationLastName: json['relationLastName'],
      religionId: json['religionId'],
      subCasteId: json['subCasteId'] as int?,
      revenueDivision: json['revenueDivision'],
      sectionName: json['sectionName'],
      voterTypeId: json['voterTypeId'],
      voterFavourToId: json['voterFavourToId'],
      policeStation: json['policeStation'],
      education: json['education'],
      occupation: json['occupation'],
      companyName: json['companyName'],
      designation: json['designation'],
      countryId: json['countryId'] as int?,
      stateId: json['stateId'],
      distId: json['distId'] as int?,
      constituencyId: json['constituencyId'] as int?,
      mandalId: json['mandalId'] as int?,
      wardVillageId: json['wardVillageId'] as int?,
      pollingBoothId: json['pollingBoothId'] as int?,
      houseNoName: json['houseNoName'],
      street: json['street'],
      postalcode: json['postalcode'] as int?,
      city: json['city'],
      isActive: json['isActive'] as int?,
      notes: json['notes'],
      houseHead: json['houseHead'],
      internalPerson: json['internalPerson'],
      ipVid: json['ipVid'],
      ipName: json['ipName'],
      ipPh: json['ipPh'],
      refVid: json['refVid'],
      refName: json['refName'],
      refPh: json['refPh'],
      xx: json['xx'],
      currLoc: json['currLoc'],
      votersCount: json['votersCount'],
      createdId: json['createdId'],
      createdDate: json['createdDate'],
      updatedId: json['updatedId'],
      updatedDate: json['updatedDate'],
    );

Map<String, dynamic> _$ImportantPeopleModelToJson(
        ImportantPeopleModel instance) =>
    <String, dynamic>{
      'voterId': instance.voterId,
      'title': instance.title,
      'first_name': instance.first_name,
      'middleName': instance.middleName,
      'lastName': instance.lastName,
      'serialNo': instance.serialNo,
      'gender': instance.gender,
      'age': instance.age,
      'dob': instance.dob,
      'phone_no': instance.phone_no,
      'emailId': instance.emailId,
      'relationType': instance.relationType,
      'relationFirstName': instance.relationFirstName,
      'relationLastName': instance.relationLastName,
      'religionId': instance.religionId,
      'subCasteId': instance.subCasteId,
      'revenueDivision': instance.revenueDivision,
      'sectionName': instance.sectionName,
      'voterTypeId': instance.voterTypeId,
      'voterFavourToId': instance.voterFavourToId,
      'policeStation': instance.policeStation,
      'education': instance.education,
      'occupation': instance.occupation,
      'companyName': instance.companyName,
      'designation': instance.designation,
      'countryId': instance.countryId,
      'stateId': instance.stateId,
      'distId': instance.distId,
      'constituencyId': instance.constituencyId,
      'mandalId': instance.mandalId,
      'wardVillageId': instance.wardVillageId,
      'pollingBoothId': instance.pollingBoothId,
      'houseNoName': instance.houseNoName,
      'street': instance.street,
      'postalcode': instance.postalcode,
      'city': instance.city,
      'isActive': instance.isActive,
      'notes': instance.notes,
      'houseHead': instance.houseHead,
      'internalPerson': instance.internalPerson,
      'ipVid': instance.ipVid,
      'ipName': instance.ipName,
      'ipPh': instance.ipPh,
      'refVid': instance.refVid,
      'refName': instance.refName,
      'refPh': instance.refPh,
      'xx': instance.xx,
      'currLoc': instance.currLoc,
      'votersCount': instance.votersCount,
      'createdId': instance.createdId,
      'createdDate': instance.createdDate,
      'updatedId': instance.updatedId,
      'updatedDate': instance.updatedDate,
    };
